wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing.yml"
    prefix:   /





wcs_coav_flight:
    resource: "@WCSCoavBundle/Resources/config/routing/flight.yml"
    prefix:   /flight


wcs_coav_reservation:
        resource: "@WCSCoavBundle/Resources/config/routing/reservation.yml"
        prefix:   /reservation

wcs_coav_terrain:
        resource: "@WCSCoavBundle/Resources/config/routing/terrain.yml"
        prefix:   /terrain
