<?php

namespace WCS\CoavBundle\Repository;

/**
 * PlanetModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneModelRepository extends \Doctrine\ORM\EntityRepository
{
}
